// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'logger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'progress_report.dart';

/// Initialize xelis_common configuration
/// This must be called before using any wallet functionality
/// It initializes VM libraries and other global configuration
Future<void> initializeXelisConfig() =>
    RustLib.instance.api.crateApiApiInitializeXelisConfig();

Future<void> initializeCryptoProvider() =>
    RustLib.instance.api.crateApiApiInitializeCryptoProvider();

Future<void> setUpRustLogger() =>
    RustLib.instance.api.crateApiApiSetUpRustLogger();

Stream<LogEntry> createLogStream() =>
    RustLib.instance.api.crateApiApiCreateLogStream();

Stream<Report> createProgressReportStream() =>
    RustLib.instance.api.crateApiApiCreateProgressReportStream();
