// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `record_to_entry`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SEND_TO_DART_LOGGER_STREAM_SINK`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_log`, `config`, `deref`, `enabled`, `flush`, `initialize`, `level`, `log`

Future<void> initLogger() => RustLib.instance.api.crateApiLoggerInitLogger();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SendToDartLogger>>
abstract class SendToDartLogger implements RustOpaqueInterface {
  LevelFilter get level;

  set level(LevelFilter level);

  static Stream<LogEntry> setStreamSink() =>
      RustLib.instance.api.crateApiLoggerSendToDartLoggerSetStreamSink();
}

enum Level {
  error,
  warn,
  info,
  debug,
  trace,
  ;
}

class LogEntry {
  final Level level;
  final String tag;
  final String msg;

  const LogEntry({
    required this.level,
    required this.tag,
    required this.msg,
  });

  @override
  int get hashCode => level.hashCode ^ tag.hashCode ^ msg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          tag == other.tag &&
          msg == other.msg;
}
