// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'precomputed_tables.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LogProgressTableGenerationReportFunction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `report`

Future<bool> arePrecomputedTablesAvailable(
        {required String precomputedTablesPath,
        required PrecomputedTableType precomputedTableType}) =>
    RustLib.instance.api.crateApiPrecomputedTablesArePrecomputedTablesAvailable(
        precomputedTablesPath: precomputedTablesPath,
        precomputedTableType: precomputedTableType);

@freezed
sealed class PrecomputedTableType with _$PrecomputedTableType {
  const PrecomputedTableType._();

  const factory PrecomputedTableType.l1Low() = PrecomputedTableType_L1Low;
  const factory PrecomputedTableType.l1Medium() = PrecomputedTableType_L1Medium;
  const factory PrecomputedTableType.l1Full() = PrecomputedTableType_L1Full;
  const factory PrecomputedTableType.custom(
    BigInt field0,
  ) = PrecomputedTableType_Custom;

  Future<int> index() =>
      RustLib.instance.api.crateApiPrecomputedTablesPrecomputedTableTypeIndex(
        that: this,
      );

  Future<String> name() =>
      RustLib.instance.api.crateApiPrecomputedTablesPrecomputedTableTypeName(
        that: this,
      );

  /// Convert to the actual L1 size used by the tables code.
  /// For Custom(n), this uses 1 << n and enforces 8 <= n <= 32.
  Future<BigInt> toL1Size() => RustLib.instance.api
          .crateApiPrecomputedTablesPrecomputedTableTypeToL1Size(
        that: this,
      );
}
