// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `from_xelis`

BigInt getLanguageIndexFromStr({required String input}) =>
    RustLib.instance.api.crateApiUtilsGetLanguageIndexFromStr(input: input);

List<String> getMnemonicWords({required BigInt languageIndex}) =>
    RustLib.instance.api
        .crateApiUtilsGetMnemonicWords(languageIndex: languageIndex);

bool isAddressValid({required String strAddress, required Network network}) =>
    RustLib.instance.api
        .crateApiUtilsIsAddressValid(strAddress: strAddress, network: network);

String splitIntegratedAddress({required String integratedAddress}) => RustLib
    .instance.api
    .crateApiUtilsSplitIntegratedAddress(integratedAddress: integratedAddress);

Future<String> formatCoin({required BigInt value, required int decimals}) =>
    RustLib.instance.api
        .crateApiUtilsFormatCoin(value: value, decimals: decimals);

Future<String> formatXelis({required BigInt value}) =>
    RustLib.instance.api.crateApiUtilsFormatXelis(value: value);
