// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models/wallet_dtos.dart';
import 'models/xswd_dtos.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'precomputed_tables.dart';
import 'xswd/imp.dart';

// These functions are ignored because they are not marked as `pub`: `build_unsigned_transaction`, `convert_float_amount`, `create_transfers`, `get_asset_data`, `get_mt_params`, `init_asset_cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_wallet`

void clearAssetCache() => RustLib.instance.api.crateApiWalletClearAssetCache();

BigInt getAssetCacheSize() =>
    RustLib.instance.api.crateApiWalletGetAssetCacheSize();

PrecomputedTablesShared? getCachedTable() =>
    RustLib.instance.api.crateApiWalletGetCachedTable();

void clearCachedTables() =>
    RustLib.instance.api.crateApiWalletClearCachedTables();

void dropWallet({required XelisWallet wallet}) =>
    RustLib.instance.api.crateApiWalletDropWallet(wallet: wallet);

void refreshMtParams() => RustLib.instance.api.crateApiWalletRefreshMtParams();

void setMtParams({required BigInt threadCount, required BigInt concurrency}) =>
    RustLib.instance.api.crateApiWalletSetMtParams(
        threadCount: threadCount, concurrency: concurrency);

Future<void> updateTables(
        {required String precomputedTablesPath,
        required PrecomputedTableType precomputedTableType}) =>
    RustLib.instance.api.crateApiWalletUpdateTables(
        precomputedTablesPath: precomputedTablesPath,
        precomputedTableType: precomputedTableType);

Future<PrecomputedTableType> getCurrentPrecomputedTablesType() =>
    RustLib.instance.api.crateApiWalletGetCurrentPrecomputedTablesType();

Future<XelisWallet> createXelisWallet(
        {required String name,
        required String directory,
        required String password,
        required Network network,
        String? seed,
        String? privateKey,
        String? precomputedTablesPath,
        required PrecomputedTableType precomputedTableType}) =>
    RustLib.instance.api.crateApiWalletCreateXelisWallet(
        name: name,
        directory: directory,
        password: password,
        network: network,
        seed: seed,
        privateKey: privateKey,
        precomputedTablesPath: precomputedTablesPath,
        precomputedTableType: precomputedTableType);

Future<XelisWallet> openXelisWallet(
        {required String name,
        required String directory,
        required String password,
        required Network network,
        String? precomputedTablesPath,
        required PrecomputedTableType precomputedTableType}) =>
    RustLib.instance.api.crateApiWalletOpenXelisWallet(
        name: name,
        directory: directory,
        password: password,
        network: network,
        precomputedTablesPath: precomputedTablesPath,
        precomputedTableType: precomputedTableType);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PrecomputedTablesShared>>
abstract class PrecomputedTablesShared implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Transaction>>
abstract class Transaction implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransactionBuilderState>>
abstract class TransactionBuilderState implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XelisWallet>>
abstract class XelisWallet implements RustOpaqueInterface, XSWD {
  Future<List<String>> allHistory();

  Future<void> broadcastTransaction({required String txHash});

  Future<void> changePassword(
      {required String oldPassword, required String newPassword});

  (Transaction, TransactionBuilderState) clearTransaction(
      {required String txHash});

  Future<void> close();

  @override
  Future<void> closeApplicationSession({required String id});

  Future<String> convertTransactionsToCsv();

  Future<String> createBurnAllTransaction({required String assetHash});

  Future<String> createBurnTransaction(
      {required double floatAmount, required String assetHash});

  Future<String> createMultisigBurnAllTransaction({required String assetHash});

  Future<String> createMultisigBurnTransaction(
      {required double floatAmount, required String assetHash});

  Future<String> createMultisigTransferAllTransaction(
      {required String strAddress,
      String? assetHash,
      String? extraData,
      bool? encryptExtraData});

  Future<String> createMultisigTransfersTransaction(
      {required List<Transfer> transfers});

  Future<String> createTransferAllTransaction(
      {required String strAddress,
      String? assetHash,
      String? extraData,
      bool? encryptExtraData});

  Future<String> createTransfersTransaction(
      {required List<Transfer> transfers});

  Future<String> estimateFees({required List<Transfer> transfers});

  Stream<String> eventsStream();

  Future<void> exportTransactionsToCsvFile({required String filePath});

  Future<String> finalizeMultisigTransaction(
      {required List<SignatureMultisig> signatures});

  Future<String> formatCoin({required BigInt atomicAmount, String? assetHash});

  String getAddressStr();

  Future<List<(String, XelisAssetMetadata)>> getAllAssets();

  @override
  Future<List<AppInfo>> getApplicationPermissions();

  Future<String> getAssetBalanceById({required String asset});

  Future<BigInt> getAssetBalanceByIdRaw({required String asset});

  Future<Map<String, String>> getAssetBalances();

  Future<int> getAssetDecimals({required String asset});

  Future<XelisAssetMetadata> getAssetMetadata({required String asset});

  Future<String> getAssetTicker({required String asset});

  Future<String> getDaemonInfo();

  Future<BigInt> getHistoryCount();

  Future<Map<String, String>> getKnownAssets();

  Future<String?> getMultisigState();

  Network getNetwork();

  Future<BigInt> getNonce();

  Future<String> getSeed({BigInt? languageIndex});

  Future<Map<String, BigInt>> getTrackedAssetBalancesRaw();

  Future<Map<String, String>> getTrackedBalances();

  Future<String> getXelisBalance();

  Future<BigInt> getXelisBalanceRaw();

  Future<bool> hasAssetBalance({required String asset});

  Future<bool> hasXelisBalance();

  Future<List<String>> history({required HistoryPageFilter filter});

  Future<String> initDeleteMultisig();

  bool isAddressValidForMultisig({required String address});

  Future<bool> isAssetTracked({required String asset});

  Future<bool> isOnline();

  Future<void> isValidPassword({required String password});

  @override
  Future<bool> isXswdRunning();

  @override
  Future<void> modifyApplicationPermissions(
      {required String id, required Map<String, PermissionPolicy> permissions});

  Future<String> multisigSetup(
      {required int threshold, required List<String> participants});

  String multisigSign({required String txHash});

  Future<void> offlineMode();

  Future<void> onlineMode({required String daemonAddress});

  Future<void> rescan({required BigInt topoheight});

  @override
  Future<void> startXswd(
      {required FutureOr<void> Function(XswdRequestSummary)
          cancelRequestDartCallback,
      required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
          requestApplicationDartCallback,
      required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
          requestPermissionDartCallback,
      required FutureOr<void> Function(XswdRequestSummary)
          appDisconnectDartCallback});

  @override
  Future<void> stopXswd();

  Future<bool> trackAsset({required String asset});

  Future<bool> untrackAsset({required String asset});
}
