// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'wallet_dtos.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MultisigDartPayload`, `ParticipantDartPayload`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IntegratedAddress>>
abstract class IntegratedAddress implements RustOpaqueInterface {
  Address get address;

  DataElement? get data;

  set address(Address address);

  set data(DataElement? data);
}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SummaryTransaction>>
abstract class SummaryTransaction implements RustOpaqueInterface {
  BigInt get fee;

  String get hash;

  TransactionTypeBuilder get transactionType;

  set fee(BigInt fee);

  set hash(String hash);

  set transactionType(TransactionTypeBuilder transactionType);
}

@freezed
sealed class HistoryPageFilter with _$HistoryPageFilter {
  const factory HistoryPageFilter({
    required BigInt page,
    BigInt? limit,
    String? assetHash,
    String? address,
    BigInt? minTopoheight,
    BigInt? maxTopoheight,
    required bool acceptIncoming,
    required bool acceptOutgoing,
    required bool acceptCoinbase,
    required bool acceptBurn,
  }) = _HistoryPageFilter;
}

@freezed
sealed class SignatureMultisig with _$SignatureMultisig {
  const factory SignatureMultisig({
    required int id,
    required String signature,
  }) = _SignatureMultisig;
}

@freezed
sealed class Transfer with _$Transfer {
  const factory Transfer({
    required double floatAmount,
    required String strAddress,
    required String assetHash,
    String? extraData,
    bool? encryptExtraData,
  }) = _Transfer;
}

@freezed
sealed class XelisAssetMetadata with _$XelisAssetMetadata {
  const factory XelisAssetMetadata({
    required String name,
    required String ticker,
    required int decimals,
    required XelisMaxSupplyMode maxSupply,
    XelisAssetOwner? owner,
  }) = _XelisAssetMetadata;
}

@freezed
sealed class XelisAssetOwner with _$XelisAssetOwner {
  const XelisAssetOwner._();

  const factory XelisAssetOwner.none() = XelisAssetOwner_None;
  const factory XelisAssetOwner.creator({
    required String contract,
    required BigInt id,
  }) = XelisAssetOwner_Creator;
  const factory XelisAssetOwner.owner({
    required String origin,
    required BigInt originId,
    required String owner,
  }) = XelisAssetOwner_Owner;
}

@freezed
sealed class XelisMaxSupplyMode with _$XelisMaxSupplyMode {
  const XelisMaxSupplyMode._();

  const factory XelisMaxSupplyMode.none() = XelisMaxSupplyMode_None;
  const factory XelisMaxSupplyMode.fixed(
    BigInt field0,
  ) = XelisMaxSupplyMode_Fixed;
  const factory XelisMaxSupplyMode.mintable(
    BigInt field0,
  ) = XelisMaxSupplyMode_Mintable;
}
