// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'xswd_dtos.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

@freezed
sealed class AppInfo with _$AppInfo {
  const factory AppInfo({
    required String id,
    required String name,
    required String description,
    String? url,
    required Map<String, PermissionPolicy> permissions,
  }) = _AppInfo;
}

enum PermissionPolicy {
  ask,
  accept,
  reject,
  ;
}

enum UserPermissionDecision {
  accept,
  reject,
  alwaysAccept,
  alwaysReject,
  ;
}

@freezed
sealed class XswdRequestSummary with _$XswdRequestSummary {
  const XswdRequestSummary._();
  const factory XswdRequestSummary({
    required XswdRequestType eventType,
    required AppInfo applicationInfo,
  }) = _XswdRequestSummary;
  bool isAppDisconnect() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsAppDisconnect(
        that: this,
      );

  bool isApplicationRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsApplicationRequest(
        that: this,
      );

  bool isCancelRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsCancelRequest(
        that: this,
      );

  bool isPermissionRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsPermissionRequest(
        that: this,
      );

  bool isPrefetchPermissionsRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsPrefetchPermissionsRequest(
        that: this,
      );

  String? permissionJson() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryPermissionJson(
        that: this,
      );

  String? prefetchPermissionsJson() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryPrefetchPermissionsJson(
        that: this,
      );
}

@freezed
sealed class XswdRequestType with _$XswdRequestType {
  const XswdRequestType._();

  const factory XswdRequestType.application() = XswdRequestType_Application;
  const factory XswdRequestType.permission(
    String field0,
  ) = XswdRequestType_Permission;
  const factory XswdRequestType.prefetchPermissions(
    String field0,
  ) = XswdRequestType_PrefetchPermissions;
  const factory XswdRequestType.cancelRequest() = XswdRequestType_CancelRequest;
  const factory XswdRequestType.appDisconnect() = XswdRequestType_AppDisconnect;
}
