// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'xswd_dtos.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

class AppInfo {
  final String id;
  final String name;
  final String description;
  final String? url;
  final Map<String, PermissionPolicy> permissions;

  const AppInfo({
    required this.id,
    required this.name,
    required this.description,
    this.url,
    required this.permissions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      url.hashCode ^
      permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          url == other.url &&
          permissions == other.permissions;
}

enum PermissionPolicy {
  ask,
  accept,
  reject,
  ;
}

enum UserPermissionDecision {
  accept,
  reject,
  alwaysAccept,
  alwaysReject,
  ;
}

class XswdRequestSummary {
  final XswdRequestType eventType;
  final AppInfo applicationInfo;

  const XswdRequestSummary({
    required this.eventType,
    required this.applicationInfo,
  });

  bool isAppDisconnect() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsAppDisconnect(
        that: this,
      );

  bool isApplicationRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsApplicationRequest(
        that: this,
      );

  bool isCancelRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsCancelRequest(
        that: this,
      );

  bool isPermissionRequest() => RustLib.instance.api
          .crateApiModelsXswdDtosXswdRequestSummaryIsPermissionRequest(
        that: this,
      );

  @override
  int get hashCode => eventType.hashCode ^ applicationInfo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XswdRequestSummary &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          applicationInfo == other.applicationInfo;
}

@freezed
sealed class XswdRequestType with _$XswdRequestType {
  const XswdRequestType._();

  const factory XswdRequestType.application() = XswdRequestType_Application;
  const factory XswdRequestType.permission(
    String field0,
  ) = XswdRequestType_Permission;
  const factory XswdRequestType.cancelRequest() = XswdRequestType_CancelRequest;
  const factory XswdRequestType.appDisconnect() = XswdRequestType_AppDisconnect;
}
