// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../models/xswd_dtos.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_event_summary`, `handle_permission_decision`, `xswd_event_name`

Future<void> xswdHandler(
        {required UnboundedReceiverXswdEvent receiver,
        required FutureOr<void> Function(XswdRequestSummary)
            cancelRequestDartCallback,
        required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
            requestApplicationDartCallback,
        required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
            requestPermissionDartCallback,
        required FutureOr<void> Function(XswdRequestSummary)
            appDisconnectDartCallback}) =>
    RustLib.instance.api.crateApiXswdImpXswdHandler(
        receiver: receiver,
        cancelRequestDartCallback: cancelRequestDartCallback,
        requestApplicationDartCallback: requestApplicationDartCallback,
        requestPermissionDartCallback: requestPermissionDartCallback,
        appDisconnectDartCallback: appDisconnectDartCallback);

Future<AppInfo> createAppInfo({required AppState state}) =>
    RustLib.instance.api.crateApiXswdImpCreateAppInfo(state: state);

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppState>>
abstract class AppState implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnboundedReceiver < XSWDEvent >>>
abstract class UnboundedReceiverXswdEvent implements RustOpaqueInterface {}

abstract class XSWD {
  Future<void> closeApplicationSession({required String id});

  Future<List<AppInfo>> getApplicationPermissions();

  Future<bool> isXswdRunning();

  Future<void> modifyApplicationPermissions(
      {required String id, required Map<String, PermissionPolicy> permissions});

  Future<void> startXswd(
      {required FutureOr<void> Function(XswdRequestSummary)
          cancelRequestDartCallback,
      required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
          requestApplicationDartCallback,
      required FutureOr<UserPermissionDecision> Function(XswdRequestSummary)
          requestPermissionDartCallback,
      required FutureOr<void> Function(XswdRequestSummary)
          appDisconnectDartCallback});

  Future<void> stopXswd();
}
